<script>
    //  <!-- try,catch,throw,finally  -->

function pjestimi(x,y){
    if(y==0) throw "Nuk lejohet pjetimi"
return x/y;
}
try{
console.log(pjestimi(10,0))
}
catch(err){
    console.log(err)
}
finally{
    console.log("finally")
}







</script>